### PR TITLE
Typescript type definitions

### LINKED ISSUE #175: Import type definitions from DefinitelyTyped
**Is your feature request related to a problem? Please describe.**
The typedefs in DefinitelyTyped are out of date, AND it takes a long time to push a PR through that repo.

**Describe the solution you'd like**
Copy the typedef files from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stellar-base into this repo, and make changes here on out.

See also https://github.com/stellar/js-stellar-sdk/issues/257 and its solution https://github.com/stellar/js-stellar-sdk/pull/258.

### PR DESCRIPTION
**Pull request by morleyzhi**
Pull in types from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stellar-base. Fixes #175.

### CODE REVIEW

**Comment by andywer** [comment]
Any reason not to merge this now? 😉🚀

**Comment by andywer** [comment]
Pinging @morleyzhi

**Comment by andywer** [comment]
LGTM, so we can add the missing types for the new methods introduced by #161.

**Comment by morleyzhi** [comment]
@Akuukis Sorry I missed this, thanks for your feedback!

About #2: Yes, please add issues for the things you think are missing!

#3 and #4: I'm guessing the reason `dtslint` didn't run is because our node version for the repo is 6.x, and one of dtslint's files or dependencies has a trailing comma in function args, which isn't supported until Node >8.x. So rather than remove it entirely, I have CI running the tests in Node 10, which also means not forcing dtslint to be run locally.

I'm going to force-merge this in right now; the tests pass on travis-ci.com.

**Pull request merged**
