### PR TITLE
Release v12.1.0

### PR DESCRIPTION
**Pull request by Shaptic**
This release includes a feature and some bug fixes.

### Added
* `TransactionBuilder` now has `addOperationAt` and `clearOperationAt` methods to allow manipulation of individual operations ([#757](https://github.com/stellar/js-stellar-base/pull/757)).

### Fixed
* Improve the efficiency and portability of asset type retrieval ([#758](https://github.com/stellar/js-stellar-base/pull/758)).
* `nativeToScVal` now correctly sorts maps lexicographically based on the keys to match what the Soroban environment expects ([#759](https://github.com/stellar/js-stellar-base/pull/759)).
* `humanizeEvents` now handles events without a `contractId` set more reliably ([#764](https://github.com/stellar/js-stellar-base/pull/764)).
* `nativeToScVal` now allows all integer types to come from strings ([#763](https://github.com/stellar/js-stellar-base/pull/763)).

### CODE REVIEW

**Comment by JuanRdBO** [comment]
LFG

**Comment by JuanRdBO** [comment]
When is this going to be released? 🙏

**Comment by Shaptic** [comment]
@JuanRdBO hopefully very soon! I want to get a couple of bug fixes in: #764 and #763, before releasing :+1:

**Review by sreuland — APPROVED** [review]

**Comment by JuanRdBO** [comment]
@Shaptic I can't see the new methods `addOperationAt` or `clearOperationAt` in the new release

**Comment by Shaptic** [comment]
@JuanRdBO forgot to add them to TypeScript defs :facepalm: fixed in #766! You can still force it via TS though.

**Comment by JuanRdBO** [comment]
> @JuanRdBO forgot to add them to TypeScript defs :facepalm: fixed in #766! You can still force it via TS though.

All good! Thanks!!

**Pull request merged**
