### PR TITLE
functional tests

### PR DESCRIPTION
**Pull request by FredericHeem**
* functional tests
* fix set trust line when limit is set
* remove dist and lib directory
* add mocha.opts to run tests directly with mocha
* currency not limited to 3 character (WIP)
* force node 0.10.x 
* add Transaction.decodeTransactionResultPair

### CODE REVIEW

**Comment by bartekn** [comment]
Hey @FredericHeem, sorry it took so long to get a review. The main reason is that I still don't have a full strategy for functional testing and then I will still have to discuss it with Stellar team so it can take some time. When it comes to review of your PR:

* functional tests

  It's not a right place for this tests. js-stellar-base was created only to provide low-level functionality and it's js-stellar-lib task to send transactions to horizon. You can read more about this separation [here](https://github.com/stellar/js-stellar-sdk#js-stellar-sdk-vs-js-stellar-base). So this tests should be in js-stellar-lib however, as state above, please hold on moving them there.

* fix set trust line when limit is set

  :+1:

* remove dist and lib directory

  Done in https://github.com/stellar/js-stellar-base/commit/5289e7cda99319480ecb13b2468db858f6671633. I had to do this myself because we made Travis responsible for publishing to npm and Bower.

* add mocha.opts to run tests directly with mocha

  :+1:

* currency not limited to 3 character (WIP)

  This has been already done in https://github.com/stellar/js-stellar-base/commit/cd0967fb04ea8f70922c4c2aa178c372eda86284.

* force node 0.10.x

  :+1:

* add Transaction.decodeTransactionResultPair

  :+1:

Could you move :+1: to a separate PR? I will close this one.

**Comment by FredericHeem** [comment]
The functional tests are using only code from *js-stellar-base* and nothing from *js-stellar-lib*, so the right place for this file is in *js-stellar-base*.
I'm too busy right now to create another PR, the code is there so help yourself.

**Comment by bartekn** [comment]
> The functional tests are using only code from js-stellar-base and nothing from js-stellar-lib, so the right place for this file is in js-stellar-base. 

You're making requests to horizon server (examples: [[1]](https://github.com/stellar/js-stellar-base/pull/19/files#diff-97984df3b05c0d35388ab0f2129521f0R64), [[2]](https://github.com/stellar/js-stellar-base/pull/19/files#diff-97984df3b05c0d35388ab0f2129521f0R86)) so this tests should be in js-stellar-lib.

**Comment by FredericHeem** [comment]
These are just helpers functions needed to exercise the *js-stellar-base* library. These tests do not use any function from *js-stellar-lib* therefore it doesn't make any sense to store them there.

**Pull request closed without merging**
